export const RESOURCE_TYPES = {
  FRIDGE_SPACE: "fridge_space",
  POWER: "power",
  WIFI: "wifi",
};

export const API_RETURN_MESSAGES = {
  RESERVE_SUCCESS: "RESERVE_SUCCESS",
  ITEM_UNAVAILABLE: "ITEM_UNAVAILABLE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NO_RESERVATION: 'NO_RESERVATION'
};
